name: Build and Deploy UniApp H5

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      # 1. 拉取代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 下载 HBuilderX ZIP
      - name: Download HBuilderX
        run: |
          curl -L -o hbuilderx.zip https://github.com/GmhLovEDM/hbuilderx/releases/download/4.87/HBuilderX.4.87.2025121004.zip
          mkdir HBuilderX
          7z x hbuilderx.zip -oHBuilderX

      # 3. 使用 HBuilderX CLI 构建 uni-app H5
      - name: Build UniApp H5
        # 强制使用 cmd shell 执行命令
        shell: cmd 
        run: |
          .\HBuilderX\HBuilderX\cli.exe publish --platform h5 --project see-u-ui


      - name: Check build output
        run: dir

      # 4. 部署到服务器（使用 rsync）
      - name: Deploy to server
        uses: burnett01/rsync-deployments@7.0.1
        with:
          # ... 保持不变
          path: unpackage/dist/build/web/
          remote_path: /www/wwwroot/demo.seeuui.cn/
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.SERVER_SSH_KEY }}